// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkqdwceoUATxVAxRyZpaORB0PBAQqqeM',
    appId: '1:592274079083:web:32a000b15e38d062e1a02e',
    messagingSenderId: '592274079083',
    projectId: 'piu-sntdnt',
    authDomain: 'piu-sntdnt.firebaseapp.com',
    storageBucket: 'piu-sntdnt.appspot.com',
    measurementId: 'G-S7DGCJ1WM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIGzjoJA4PqyPD80FAYKaX8M5O25sUXc',
    appId: '1:592274079083:android:453243cfd488136ee1a02e',
    messagingSenderId: '592274079083',
    projectId: 'piu-sntdnt',
    storageBucket: 'piu-sntdnt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIcvpazstcLgKqvVBKENxRU9TlgFe014',
    appId: '1:592274079083:ios:e058dbb67b4fd012e1a02e',
    messagingSenderId: '592274079083',
    projectId: 'piu-sntdnt',
    storageBucket: 'piu-sntdnt.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEIcvpazstcLgKqvVBKENxRU9TlgFe014',
    appId: '1:592274079083:ios:e058dbb67b4fd012e1a02e',
    messagingSenderId: '592274079083',
    projectId: 'piu-sntdnt',
    storageBucket: 'piu-sntdnt.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNkqdwceoUATxVAxRyZpaORB0PBAQqqeM',
    appId: '1:592274079083:web:bb5678ac65608f76e1a02e',
    messagingSenderId: '592274079083',
    projectId: 'piu-sntdnt',
    authDomain: 'piu-sntdnt.firebaseapp.com',
    storageBucket: 'piu-sntdnt.appspot.com',
    measurementId: 'G-VY3N6NCH6N',
  );
}